
__cur__ = {"Algorand": ["ALGO","ALGOEUR"],
            "Augur": ["REP","XREPZEUR"],
            "Augur v2": ["REPV2","REPV2EUR"],
            "Basic Attention Token": ["BAT","BATEUR"],
            "Balancer": ["BAL","BALEUR"],
            "Bitcoin": ["XBT","XXBTZEUR"],
            "Bitcoin Cash": ["BCH","BCHEUR"],
            "Cardano": ["ADA","ADAEUR"],
            "Chainlink": ["LINK","LINKEUR"],
            "Compound": ["COMP","COMPEUR"],
            "Cosmos": ["ATOM","ATOMEUR"],
            "Curve": ["CRV","CRVEUR"],
            "Dai": ["DAI","DAIEUR"],
            "Dash": ["DASH","DASHEUR"],
            "Dogecoin": ["XDG","XDGEUR"],
            "EOS": ["EOS","EOSEUR"],
            "Ethereum": ["ETH","XETHZEUR"],
            "Ethereum Classic": ["ETC","XETCZEUR"],
            "Filecoin": ["FIL","FILEUR"],
            "Gnosis": ["GNO","GNOEUR"],
            "ICON": ["ICX","ICXEUR"],
            "Kava": ["KAVA","KAVAEUR"],
            "Kusama": ["KSM","KSMEUR"],
            "Kyber Network": ["KNC","KNCEUR"],
            "Lisk": ["LSK","LSKEUR"],
            "Litecoin": ["LTC","XLTCZEUR"],
            "Melon": ["MLN","XMLNZEUR"],
            "Monero": ["XMR","XXMRZEUR"],
            "Nano": ["NANO","NANOEUR"],
            "OmiseGO": ["OMG","OMGEUR"],
            "Orchid": ["OXT","OXTEUR"],
            "PAX Gold": ["PAXG","PAXGEUR"],
            "Polkadot": ["DOT","DOTEUR"],
            "QTUM": ["QTUM","QTUMEUR"],
            "Ripple": ["XRP","XXRPZEUR"],
            "Siacoin": ["SC","SCEUR"],
            "Stellar Lumens": ["XLM","XXLMZEUR"],
            "Storj": ["STORJ","STORJEUR"],
            "Synthetix": ["SNX","SNXEUR"],
            "Tether": ["USDT","USDTEUR"],
            "Tezos": ["XTZ","XTZEUR"],
            "Tron": ["TRX","TRXEUR"],
            "Uniswap": ["UNI","UNIEUR"],
            "USD Coin": ["USDC","USDCEUR"],
            "Waves": ["WAVES","WAVESEUR"],
            "Yearn Finance": ["YFI","YFIEUR"],
            "Zcash": ["ZEC","XZECZEUR"]}